Integrated Mayhem
mayhemheroes/cascadia-go pull request #1
Opened 2022-05-26 02:05 UTC by bmwtsn098

2022-07-27 07:25 UTC, xansec requested changes

2022-07-27 07:25 UTC, xansec commented on Dockerfile
> +RUN go build
Can we add a package stage here?

2022-07-27 07:25 UTC, xansec commented on Mayhemfile
> +project: bmwtsn098/cascadia-test
You can use a generic project name.

2022-07-27 07:25 UTC, xansec commented on Mayhemfile
> +image: ghcr.io/bmwtsn098/cascadia:latest
And omit the image name.

2022-07-29 05:15 UTC, bmwtsn098 commented
I've made the requested changes. Let me know if everything looks good. Thanks

2022-08-01 15:44 UTC, xansec commented
LGTM!

2022-08-01 15:44 UTC, merged